apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-sep4-3-app
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/rag-sep4-3/overlays/development
    repoURL: https://github.com/redhat-appstudio-mjf/rag-sep4-3-gitops.git
    targetRevision: main
  destination:
    namespace: rag-sep4-3
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
