apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag-sep4-3
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag-sep4-3:3d20094bd86a780e3578fcaefd3fdc94edf1bd9d@sha256:430c4e5318d1bb955a54e641463eac028e95cbd1ee85fb48174b3b1cdec21097 # use pre-built to bootstrap 
          name: app-inference
